/* Add the country names and codes */

INSERT INTO country (name, code) VALUES ('Afghanistan', 'af');
INSERT INTO country (name, code) VALUES ('Albania', 'al');
INSERT INTO country (name, code) VALUES ('Algeria', 'dz');
INSERT INTO country (name, code) VALUES ('American Samoa', 'as');
INSERT INTO country (name, code) VALUES ('Andorra', 'ad');
INSERT INTO country (name, code) VALUES ('Angola', 'ao');
INSERT INTO country (name, code) VALUES ('Anguilla', 'ai');
INSERT INTO country (name, code) VALUES ('Antarctica', 'aq');
INSERT INTO country (name, code) VALUES ('Antigua & Barbuda', 'ag');
INSERT INTO country (name, code) VALUES ('Argentina', 'ar');
INSERT INTO country (name, code) VALUES ('Armenia', 'am');
INSERT INTO country (name, code) VALUES ('Aruba', 'aw');
INSERT INTO country (name, code) VALUES ('Australia', 'au');
INSERT INTO country (name, code) VALUES ('Austria', 'at');
INSERT INTO country (name, code) VALUES ('Azerbaijan', 'az');
INSERT INTO country (name, code) VALUES ('Bahama', 'bs');
INSERT INTO country (name, code) VALUES ('Bahrain', 'bh');
INSERT INTO country (name, code) VALUES ('Bangladesh', 'bd');
INSERT INTO country (name, code) VALUES ('Barbados', 'bb');
INSERT INTO country (name, code) VALUES ('Belarus', 'by');
INSERT INTO country (name, code) VALUES ('Belgium', 'be');
INSERT INTO country (name, code) VALUES ('Belize', 'bz');
INSERT INTO country (name, code) VALUES ('Benin', 'bj');
INSERT INTO country (name, code) VALUES ('Bermuda', 'bm');
INSERT INTO country (name, code) VALUES ('Bhutan', 'bt');
INSERT INTO country (name, code) VALUES ('Bolivia', 'bo');
INSERT INTO country (name, code) VALUES ('Bosnia and Herzegovina', 'ba');
INSERT INTO country (name, code) VALUES ('Botswana', 'bw');
INSERT INTO country (name, code) VALUES ('Bouvet Island', 'bv');
INSERT INTO country (name, code) VALUES ('Brazil', 'br');
INSERT INTO country (name, code) VALUES ('British Indian Ocean Territory', 'io');
INSERT INTO country (name, code) VALUES ('British Virgin Islands', 'vg');
INSERT INTO country (name, code) VALUES ('Brunei Darussalam', 'bn');
INSERT INTO country (name, code) VALUES ('Bulgaria', 'bg');
INSERT INTO country (name, code) VALUES ('Burkina Faso', 'bf');
INSERT INTO country (name, code) VALUES ('Burma (no longer exists)', 'bu');
INSERT INTO country (name, code) VALUES ('Burundi', 'bi');
INSERT INTO country (name, code) VALUES ('Cambodia', 'kh');
INSERT INTO country (name, code) VALUES ('Cameroon', 'cm');
INSERT INTO country (name, code) VALUES ('Canada', 'ca');
INSERT INTO country (name, code) VALUES ('Cape Verde', 'cv');
INSERT INTO country (name, code) VALUES ('Cayman Islands', 'ky');
INSERT INTO country (name, code) VALUES ('Central African Republic', 'cf');
INSERT INTO country (name, code) VALUES ('Chad', 'td');
INSERT INTO country (name, code) VALUES ('Chile', 'cl');
INSERT INTO country (name, code) VALUES ('China', 'cn');
INSERT INTO country (name, code) VALUES ('Christmas Island', 'cx');
INSERT INTO country (name, code) VALUES ('Cocos (Keeling) Islands', 'cc');
INSERT INTO country (name, code) VALUES ('Colombia', 'co');
INSERT INTO country (name, code) VALUES ('Comoros', 'km');
INSERT INTO country (name, code) VALUES ('Congo', 'cg');
INSERT INTO country (name, code) VALUES ('Cook Iislands', 'ck');
INSERT INTO country (name, code) VALUES ('Costa Rica', 'cr');
INSERT INTO country (name, code) VALUES ('Croatia', 'hr');
INSERT INTO country (name, code) VALUES ('Cuba', 'cu');
INSERT INTO country (name, code) VALUES ('Cyprus', 'cy');
INSERT INTO country (name, code) VALUES ('Czech Republic', 'cz');
INSERT INTO country (name, code) VALUES ('Czechoslovakia (no longer exists)', 'cs');
INSERT INTO country (name, code) VALUES ('Côte D''ivoire (Ivory Coast)', 'ci');
INSERT INTO country (name, code) VALUES ('Democratic Yemen (no longer exists)', 'yd');
INSERT INTO country (name, code) VALUES ('Denmark', 'dk');
INSERT INTO country (name, code) VALUES ('Djibouti', 'dj');
INSERT INTO country (name, code) VALUES ('Dominica', 'dm');
INSERT INTO country (name, code) VALUES ('Dominican Republic', 'do');
INSERT INTO country (name, code) VALUES ('East Timor', 'tp');
INSERT INTO country (name, code) VALUES ('Ecuador', 'ec');
INSERT INTO country (name, code) VALUES ('Egypt', 'eg');
INSERT INTO country (name, code) VALUES ('El Salvador', 'sv');
INSERT INTO country (name, code) VALUES ('Equatorial Guinea', 'gq');
INSERT INTO country (name, code) VALUES ('Eritrea', 'er');
INSERT INTO country (name, code) VALUES ('Estonia', 'ee');
INSERT INTO country (name, code) VALUES ('Ethiopia', 'et');
INSERT INTO country (name, code) VALUES ('Falkland Islands (Malvinas)', 'fk');
INSERT INTO country (name, code) VALUES ('Faroe Islands', 'fo');
INSERT INTO country (name, code) VALUES ('Fiji', 'fj');
INSERT INTO country (name, code) VALUES ('Finland', 'fi');
INSERT INTO country (name, code) VALUES ('France', 'fr');
INSERT INTO country (name, code) VALUES ('French Guiana', 'gf');
INSERT INTO country (name, code) VALUES ('French Polynesia', 'pf');
INSERT INTO country (name, code) VALUES ('French Southern Territories', 'tf');
INSERT INTO country (name, code) VALUES ('Gabon', 'ga');
INSERT INTO country (name, code) VALUES ('Gambia', 'gm');
INSERT INTO country (name, code) VALUES ('Georgia', 'ge');
INSERT INTO country (name, code) VALUES ('German Democratic Republic (no longer exists)', 'dd');
INSERT INTO country (name, code) VALUES ('Germany', 'de');
INSERT INTO country (name, code) VALUES ('Ghana', 'gh');
INSERT INTO country (name, code) VALUES ('Gibraltar', 'gi');
INSERT INTO country (name, code) VALUES ('Greece', 'gr');
INSERT INTO country (name, code) VALUES ('Greenland', 'gl');
INSERT INTO country (name, code) VALUES ('Grenada', 'gd');
INSERT INTO country (name, code) VALUES ('Guadeloupe', 'gp');
INSERT INTO country (name, code) VALUES ('Guam', 'gu');
INSERT INTO country (name, code) VALUES ('Guatemala', 'gt');
INSERT INTO country (name, code) VALUES ('Guinea', 'gn');
INSERT INTO country (name, code) VALUES ('Guinea-Bissau', 'gw');
INSERT INTO country (name, code) VALUES ('Guyana', 'gy');
INSERT INTO country (name, code) VALUES ('Haiti', 'ht');
INSERT INTO country (name, code) VALUES ('Heard & McDonald Islands', 'hm');
INSERT INTO country (name, code) VALUES ('Honduras', 'hn');
INSERT INTO country (name, code) VALUES ('Hong Kong', 'hk');
INSERT INTO country (name, code) VALUES ('Hungary', 'hu');
INSERT INTO country (name, code) VALUES ('Iceland', 'is');
INSERT INTO country (name, code) VALUES ('India', 'in');
INSERT INTO country (name, code) VALUES ('Indonesia', 'id');
INSERT INTO country (name, code) VALUES ('Iraq', 'iq');
INSERT INTO country (name, code) VALUES ('Ireland', 'ie');
INSERT INTO country (name, code) VALUES ('Islamic Republic of Iran', 'ir');
INSERT INTO country (name, code) VALUES ('Israel', 'il');
INSERT INTO country (name, code) VALUES ('Italy', 'it');
INSERT INTO country (name, code) VALUES ('Jamaica', 'jm');
INSERT INTO country (name, code) VALUES ('Japan', 'jp');
INSERT INTO country (name, code) VALUES ('Jordan', 'jo');
INSERT INTO country (name, code) VALUES ('Kazakhstan', 'kz');
INSERT INTO country (name, code) VALUES ('Kenya', 'ke');
INSERT INTO country (name, code) VALUES ('Kiribati', 'ki');
INSERT INTO country (name, code) VALUES ('Korea, Democratic People''s Republic of', 'kp');
INSERT INTO country (name, code) VALUES ('Korea, Republic of', 'kr');
INSERT INTO country (name, code) VALUES ('Kuwait', 'kw');
INSERT INTO country (name, code) VALUES ('Kyrgyzstan', 'kg');
INSERT INTO country (name, code) VALUES ('Lao People''s Democratic Republic', 'la');
INSERT INTO country (name, code) VALUES ('Latvia', 'lv');
INSERT INTO country (name, code) VALUES ('Lebanon', 'lb');
INSERT INTO country (name, code) VALUES ('Lesotho', 'ls');
INSERT INTO country (name, code) VALUES ('Liberia', 'lr');
INSERT INTO country (name, code) VALUES ('Libyan Arab Jamahiriya', 'ly');
INSERT INTO country (name, code) VALUES ('Liechtenstein', 'li');
INSERT INTO country (name, code) VALUES ('Lithuania', 'lt');
INSERT INTO country (name, code) VALUES ('Luxembourg', 'lu');
INSERT INTO country (name, code) VALUES ('Macau', 'mo');
INSERT INTO country (name, code) VALUES ('Madagascar', 'mg');
INSERT INTO country (name, code) VALUES ('Malawi', 'mw');
INSERT INTO country (name, code) VALUES ('Malaysia', 'my');
INSERT INTO country (name, code) VALUES ('Maldives', 'mv');
INSERT INTO country (name, code) VALUES ('Mali', 'ml');
INSERT INTO country (name, code) VALUES ('Malta', 'mt');
INSERT INTO country (name, code) VALUES ('Marshall Islands', 'mh');
INSERT INTO country (name, code) VALUES ('Martinique', 'mq');
INSERT INTO country (name, code) VALUES ('Mauritania', 'mr');
INSERT INTO country (name, code) VALUES ('Mauritius', 'mu');
INSERT INTO country (name, code) VALUES ('Mayotte', 'yt');
INSERT INTO country (name, code) VALUES ('Mexico', 'mx');
INSERT INTO country (name, code) VALUES ('Micronesia', 'fm');
INSERT INTO country (name, code) VALUES ('Moldova, Republic of', 'md');
INSERT INTO country (name, code) VALUES ('Monaco', 'mc');
INSERT INTO country (name, code) VALUES ('Mongolia', 'mn');
INSERT INTO country (name, code) VALUES ('Monserrat', 'ms');
INSERT INTO country (name, code) VALUES ('Morocco', 'ma');
INSERT INTO country (name, code) VALUES ('Mozambique', 'mz');
INSERT INTO country (name, code) VALUES ('Myanmar', 'mm');
INSERT INTO country (name, code) VALUES ('Namibia', 'na');
INSERT INTO country (name, code) VALUES ('Nauru', 'nr');
INSERT INTO country (name, code) VALUES ('Nepal', 'np');
INSERT INTO country (name, code) VALUES ('Netherlands Antilles', 'an');
INSERT INTO country (name, code) VALUES ('Netherlands', 'nl');
INSERT INTO country (name, code) VALUES ('Neutral Zone (no longer exists)', 'nt');
INSERT INTO country (name, code) VALUES ('New Caledonia', 'nc');
INSERT INTO country (name, code) VALUES ('New Zealand', 'nz');
INSERT INTO country (name, code) VALUES ('Nicaragua', 'ni');
INSERT INTO country (name, code) VALUES ('Niger', 'ne');
INSERT INTO country (name, code) VALUES ('Nigeria', 'ng');
INSERT INTO country (name, code) VALUES ('Niue', 'nu');
INSERT INTO country (name, code) VALUES ('Norfolk Island', 'nf');
INSERT INTO country (name, code) VALUES ('Northern Mariana Islands', 'mp');
INSERT INTO country (name, code) VALUES ('Norway', 'no');
INSERT INTO country (name, code) VALUES ('Oman', 'om');
INSERT INTO country (name, code) VALUES ('Pakistan', 'pk');
INSERT INTO country (name, code) VALUES ('Palau', 'pw');
INSERT INTO country (name, code) VALUES ('Panama', 'pa');
INSERT INTO country (name, code) VALUES ('Papua New Guinea', 'pg');
INSERT INTO country (name, code) VALUES ('Paraguay', 'py');
INSERT INTO country (name, code) VALUES ('Peru', 'pe');
INSERT INTO country (name, code) VALUES ('Philippines', 'ph');
INSERT INTO country (name, code) VALUES ('Pitcairn', 'pn');
INSERT INTO country (name, code) VALUES ('Poland', 'pl');
INSERT INTO country (name, code) VALUES ('Portugal', 'pt');
INSERT INTO country (name, code) VALUES ('Puerto Rico', 'pr');
INSERT INTO country (name, code) VALUES ('Qatar', 'qa');
INSERT INTO country (name, code) VALUES ('Romania', 'ro');
INSERT INTO country (name, code) VALUES ('Russian Federation', 'ru');
INSERT INTO country (name, code) VALUES ('Rwanda', 'rw');
INSERT INTO country (name, code) VALUES ('Réunion', 're');
INSERT INTO country (name, code) VALUES ('Saint Lucia', 'lc');
INSERT INTO country (name, code) VALUES ('Samoa', 'ws');
INSERT INTO country (name, code) VALUES ('San Marino', 'sm');
INSERT INTO country (name, code) VALUES ('Sao Tome & Principe', 'st');
INSERT INTO country (name, code) VALUES ('Saudi Arabia', 'sa');
INSERT INTO country (name, code) VALUES ('Senegal', 'sn');
INSERT INTO country (name, code) VALUES ('Seychelles', 'sc');
INSERT INTO country (name, code) VALUES ('Sierra Leone', 'sl');
INSERT INTO country (name, code) VALUES ('Singapore', 'sg');
INSERT INTO country (name, code) VALUES ('Slovakia', 'sk');
INSERT INTO country (name, code) VALUES ('Slovenia', 'si');
INSERT INTO country (name, code) VALUES ('Solomon Islands', 'sb');
INSERT INTO country (name, code) VALUES ('Somalia', 'so');
INSERT INTO country (name, code) VALUES ('South Africa', 'za');
INSERT INTO country (name, code) VALUES ('South Georgia and the South Sandwich Islands', 'gs');
INSERT INTO country (name, code) VALUES ('Spain', 'es');
INSERT INTO country (name, code) VALUES ('Sri Lanka', 'lk');
INSERT INTO country (name, code) VALUES ('St. Helena', 'sh');
INSERT INTO country (name, code) VALUES ('St. Kitts and Nevis', 'kn');
INSERT INTO country (name, code) VALUES ('St. Pierre & Miquelon', 'pm');
INSERT INTO country (name, code) VALUES ('St. Vincent & the Grenadines', 'vc');
INSERT INTO country (name, code) VALUES ('Sudan', 'sd');
INSERT INTO country (name, code) VALUES ('Suriname', 'sr');
INSERT INTO country (name, code) VALUES ('Svalbard & Jan Mayen Islands', 'sj');
INSERT INTO country (name, code) VALUES ('Swaziland', 'sz');
INSERT INTO country (name, code) VALUES ('Sweden', 'se');
INSERT INTO country (name, code) VALUES ('Switzerland', 'ch');
INSERT INTO country (name, code) VALUES ('Syrian Arab Republic', 'sy');
INSERT INTO country (name, code) VALUES ('Taiwan, Province of China', 'tw');
INSERT INTO country (name, code) VALUES ('Tajikistan', 'tj');
INSERT INTO country (name, code) VALUES ('Tanzania, United Republic of', 'tz');
INSERT INTO country (name, code) VALUES ('Thailand', 'th');
INSERT INTO country (name, code) VALUES ('Togo', 'tg');
INSERT INTO country (name, code) VALUES ('Tokelau', 'tk');
INSERT INTO country (name, code) VALUES ('Tonga', 'to');
INSERT INTO country (name, code) VALUES ('Trinidad & Tobago', 'tt');
INSERT INTO country (name, code) VALUES ('Tunisia', 'tn');
INSERT INTO country (name, code) VALUES ('Turkey', 'tr');
INSERT INTO country (name, code) VALUES ('Turkmenistan', 'tm');
INSERT INTO country (name, code) VALUES ('Turks & Caicos Islands', 'tc');
INSERT INTO country (name, code) VALUES ('Tuvalu', 'tv');
INSERT INTO country (name, code) VALUES ('Uganda', 'ug');
INSERT INTO country (name, code) VALUES ('Ukraine', 'ua');
INSERT INTO country (name, code) VALUES ('Union of Soviet Socialist Republics (no longer exists)', 'su');
INSERT INTO country (name, code) VALUES ('United Arab Emirates', 'ae');
INSERT INTO country (name, code) VALUES ('United Kingdom (Great Britain)', 'gb');
INSERT INTO country (name, code) VALUES ('United States Minor Outlying Islands', 'um');
INSERT INTO country (name, code) VALUES ('United States Virgin Islands', 'vi');
INSERT INTO country (name, code) VALUES ('United States', 'us');
INSERT INTO country (name, code) VALUES ('Uruguay', 'uy');
INSERT INTO country (name, code) VALUES ('Uzbekistan', 'uz');
INSERT INTO country (name, code) VALUES ('Vanuatu', 'vu');
INSERT INTO country (name, code) VALUES ('Vatican City State (Holy See)', 'va');
INSERT INTO country (name, code) VALUES ('Venezuela', 've');
INSERT INTO country (name, code) VALUES ('Viet Nam', 'vn');
INSERT INTO country (name, code) VALUES ('Wallis & Futuna Islands', 'wf');
INSERT INTO country (name, code) VALUES ('Western Sahara', 'eh');
INSERT INTO country (name, code) VALUES ('Yemen', 'ye');
INSERT INTO country (name, code) VALUES ('Yugoslavia', 'yu');
INSERT INTO country (name, code) VALUES ('Zaire', 'zr');
INSERT INTO country (name, code) VALUES ('Zambia', 'zm');
INSERT INTO country (name, code) VALUES ('Zimbabwe', 'zw');