/* Add the country names and codes */

INSERT INTO country (id, name, code) VALUES (1,'Afghanistan','af');
INSERT INTO country (id, name, code) VALUES (2,'Albania','al');
INSERT INTO country (id, name, code) VALUES (3,'Algeria','dz');
INSERT INTO country (id, name, code) VALUES (4,'American Samoa','as');
INSERT INTO country (id, name, code) VALUES (5,'Andorra','ad');
INSERT INTO country (id, name, code) VALUES (6,'Angola','ao');
INSERT INTO country (id, name, code) VALUES (7,'Anguilla','ai');
INSERT INTO country (id, name, code) VALUES (8,'Antarctica','aq');
INSERT INTO country (id, name, code) VALUES (9,'Antigua & Barbuda','ag');
INSERT INTO country (id, name, code) VALUES (10,'Argentina','ar');
INSERT INTO country (id, name, code) VALUES (11,'Armenia','am');
INSERT INTO country (id, name, code) VALUES (12,'Aruba','aw');
INSERT INTO country (id, name, code) VALUES (13,'Australia','au');
INSERT INTO country (id, name, code) VALUES (14,'Austria','at');
INSERT INTO country (id, name, code) VALUES (15,'Azerbaijan','az');
INSERT INTO country (id, name, code) VALUES (16,'Bahama','bs');
INSERT INTO country (id, name, code) VALUES (17,'Bahrain','bh');
INSERT INTO country (id, name, code) VALUES (18,'Bangladesh','bd');
INSERT INTO country (id, name, code) VALUES (19,'Barbados','bb');
INSERT INTO country (id, name, code) VALUES (20,'Belarus','by');
INSERT INTO country (id, name, code) VALUES (21,'Belgium','be');
INSERT INTO country (id, name, code) VALUES (22,'Belize','bz');
INSERT INTO country (id, name, code) VALUES (23,'Benin','bj');
INSERT INTO country (id, name, code) VALUES (24,'Bermuda','bm');
INSERT INTO country (id, name, code) VALUES (25,'Bhutan','bt');
INSERT INTO country (id, name, code) VALUES (26,'Bolivia','bo');
INSERT INTO country (id, name, code) VALUES (27,'Bosnia and Herzegovina','ba');
INSERT INTO country (id, name, code) VALUES (28,'Botswana','bw');
INSERT INTO country (id, name, code) VALUES (29,'Bouvet Island','bv');
INSERT INTO country (id, name, code) VALUES (30,'Brazil','br');
INSERT INTO country (id, name, code) VALUES (31,'British Indian Ocean Territory','io');
INSERT INTO country (id, name, code) VALUES (32,'British Virgin Islands','vg');
INSERT INTO country (id, name, code) VALUES (33,'Brunei Darussalam','bn');
INSERT INTO country (id, name, code) VALUES (34,'Bulgaria','bg');
INSERT INTO country (id, name, code) VALUES (35,'Burkina Faso','bf');
INSERT INTO country (id, name, code) VALUES (36,'Burma (no longer exists)','bu');
INSERT INTO country (id, name, code) VALUES (37,'Burundi','bi');
INSERT INTO country (id, name, code) VALUES (38,'Cambodia','kh');
INSERT INTO country (id, name, code) VALUES (39,'Cameroon','cm');
INSERT INTO country (id, name, code) VALUES (40,'Canada','ca');
INSERT INTO country (id, name, code) VALUES (41,'Cape Verde','cv');
INSERT INTO country (id, name, code) VALUES (42,'Cayman Islands','ky');
INSERT INTO country (id, name, code) VALUES (43,'Central African Republic','cf');
INSERT INTO country (id, name, code) VALUES (44,'Chad','td');
INSERT INTO country (id, name, code) VALUES (45,'Chile','cl');
INSERT INTO country (id, name, code) VALUES (46,'China','cn');
INSERT INTO country (id, name, code) VALUES (47,'Christmas Island','cx');
INSERT INTO country (id, name, code) VALUES (48,'Cocos (Keeling) Islands','cc');
INSERT INTO country (id, name, code) VALUES (49,'Colombia','co');
INSERT INTO country (id, name, code) VALUES (50,'Comoros','km');
INSERT INTO country (id, name, code) VALUES (51,'Congo','cg');
INSERT INTO country (id, name, code) VALUES (52,'Cook Islands','ck');
INSERT INTO country (id, name, code) VALUES (53,'Costa Rica','cr');
INSERT INTO country (id, name, code) VALUES (54,'Croatia','hr');
INSERT INTO country (id, name, code) VALUES (55,'Cuba','cu');
INSERT INTO country (id, name, code) VALUES (56,'Cyprus','cy');
INSERT INTO country (id, name, code) VALUES (57,'Czech Republic','cz');
INSERT INTO country (id, name, code) VALUES (58,'Czechoslovakia (no longer exists)','cs');
INSERT INTO country (id, name, code) VALUES (59,'Côte D''ivoire (Ivory Coast)','ci');
INSERT INTO country (id, name, code) VALUES (60,'Democratic Yemen (no longer exists)','yd');
INSERT INTO country (id, name, code) VALUES (61,'Denmark','dk');
INSERT INTO country (id, name, code) VALUES (62,'Djibouti','dj');
INSERT INTO country (id, name, code) VALUES (63,'Dominica','dm');
INSERT INTO country (id, name, code) VALUES (64,'Dominican Republic','do');
INSERT INTO country (id, name, code) VALUES (65,'East Timor','tp');
INSERT INTO country (id, name, code) VALUES (66,'Ecuador','ec');
INSERT INTO country (id, name, code) VALUES (67,'Egypt','eg');
INSERT INTO country (id, name, code) VALUES (68,'El Salvador','sv');
INSERT INTO country (id, name, code) VALUES (69,'Equatorial Guinea','gq');
INSERT INTO country (id, name, code) VALUES (70,'Eritrea','er');
INSERT INTO country (id, name, code) VALUES (71,'Estonia','ee');
INSERT INTO country (id, name, code) VALUES (72,'Ethiopia','et');
INSERT INTO country (id, name, code) VALUES (73,'Falkland Islands (Malvinas)','fk');
INSERT INTO country (id, name, code) VALUES (74,'Faroe Islands','fo');
INSERT INTO country (id, name, code) VALUES (75,'Fiji','fj');
INSERT INTO country (id, name, code) VALUES (76,'Finland','fi');
INSERT INTO country (id, name, code) VALUES (77,'France','fr');
INSERT INTO country (id, name, code) VALUES (78,'French Guiana','gf');
INSERT INTO country (id, name, code) VALUES (79,'French Polynesia','pf');
INSERT INTO country (id, name, code) VALUES (80,'French Southern Territories','tf');
INSERT INTO country (id, name, code) VALUES (81,'Gabon','ga');
INSERT INTO country (id, name, code) VALUES (82,'Gambia','gm');
INSERT INTO country (id, name, code) VALUES (83,'Georgia','ge');
INSERT INTO country (id, name, code) VALUES (84,'German Democratic Republic (no longer exists)','dd');
INSERT INTO country (id, name, code) VALUES (85,'Germany','de');
INSERT INTO country (id, name, code) VALUES (86,'Ghana','gh');
INSERT INTO country (id, name, code) VALUES (87,'Gibraltar','gi');
INSERT INTO country (id, name, code) VALUES (88,'Greece','gr');
INSERT INTO country (id, name, code) VALUES (89,'Greenland','gl');
INSERT INTO country (id, name, code) VALUES (90,'Grenada','gd');
INSERT INTO country (id, name, code) VALUES (91,'Guadeloupe','gp');
INSERT INTO country (id, name, code) VALUES (92,'Guam','gu');
INSERT INTO country (id, name, code) VALUES (93,'Guatemala','gt');
INSERT INTO country (id, name, code) VALUES (94,'Guinea','gn');
INSERT INTO country (id, name, code) VALUES (95,'Guinea-Bissau','gw');
INSERT INTO country (id, name, code) VALUES (96,'Guyana','gy');
INSERT INTO country (id, name, code) VALUES (97,'Haiti','ht');
INSERT INTO country (id, name, code) VALUES (98,'Heard & McDonald Islands','hm');
INSERT INTO country (id, name, code) VALUES (99,'Honduras','hn');
INSERT INTO country (id, name, code) VALUES (100,'Hong Kong','hk');
INSERT INTO country (id, name, code) VALUES (101,'Hungary','hu');
INSERT INTO country (id, name, code) VALUES (102,'Iceland','is');
INSERT INTO country (id, name, code) VALUES (103,'India','in');
INSERT INTO country (id, name, code) VALUES (104,'Indonesia','id');
INSERT INTO country (id, name, code) VALUES (105,'Iraq','iq');
INSERT INTO country (id, name, code) VALUES (106,'Ireland','ie');
INSERT INTO country (id, name, code) VALUES (107,'Islamic Republic of Iran','ir');
INSERT INTO country (id, name, code) VALUES (108,'Israel','il');
INSERT INTO country (id, name, code) VALUES (109,'Italy','it');
INSERT INTO country (id, name, code) VALUES (110,'Jamaica','jm');
INSERT INTO country (id, name, code) VALUES (111,'Japan','jp');
INSERT INTO country (id, name, code) VALUES (112,'Jordan','jo');
INSERT INTO country (id, name, code) VALUES (113,'Kazakhstan','kz');
INSERT INTO country (id, name, code) VALUES (114,'Kenya','ke');
INSERT INTO country (id, name, code) VALUES (115,'Kiribati','ki');
INSERT INTO country (id, name, code) VALUES (116,'Korea, Democratic People''s Republic of','kp');
INSERT INTO country (id, name, code) VALUES (117,'Korea, Republic of','kr');
INSERT INTO country (id, name, code) VALUES (118,'Kuwait','kw');
INSERT INTO country (id, name, code) VALUES (119,'Kyrgyzstan','kg');
INSERT INTO country (id, name, code) VALUES (120,'Lao People''s Democratic Republic','la');
INSERT INTO country (id, name, code) VALUES (121,'Latvia','lv');
INSERT INTO country (id, name, code) VALUES (122,'Lebanon','lb');
INSERT INTO country (id, name, code) VALUES (123,'Lesotho','ls');
INSERT INTO country (id, name, code) VALUES (124,'Liberia','lr');
INSERT INTO country (id, name, code) VALUES (125,'Libyan Arab Jamahiriya','ly');
INSERT INTO country (id, name, code) VALUES (126,'Liechtenstein','li');
INSERT INTO country (id, name, code) VALUES (127,'Lithuania','lt');
INSERT INTO country (id, name, code) VALUES (128,'Luxembourg','lu');
INSERT INTO country (id, name, code) VALUES (129,'Macau','mo');
INSERT INTO country (id, name, code) VALUES (130,'Madagascar','mg');
INSERT INTO country (id, name, code) VALUES (131,'Malawi','mw');
INSERT INTO country (id, name, code) VALUES (132,'Malaysia','my');
INSERT INTO country (id, name, code) VALUES (133,'Maldives','mv');
INSERT INTO country (id, name, code) VALUES (134,'Mali','ml');
INSERT INTO country (id, name, code) VALUES (135,'Malta','mt');
INSERT INTO country (id, name, code) VALUES (136,'Marshall Islands','mh');
INSERT INTO country (id, name, code) VALUES (137,'Martinique','mq');
INSERT INTO country (id, name, code) VALUES (138,'Mauritania','mr');
INSERT INTO country (id, name, code) VALUES (139,'Mauritius','mu');
INSERT INTO country (id, name, code) VALUES (140,'Mayotte','yt');
INSERT INTO country (id, name, code) VALUES (141,'Mexico','mx');
INSERT INTO country (id, name, code) VALUES (142,'Micronesia','fm');
INSERT INTO country (id, name, code) VALUES (143,'Moldova, Republic of','md');
INSERT INTO country (id, name, code) VALUES (144,'Monaco','mc');
INSERT INTO country (id, name, code) VALUES (145,'Mongolia','mn');
INSERT INTO country (id, name, code) VALUES (146,'Monserrat','ms');
INSERT INTO country (id, name, code) VALUES (147,'Morocco','ma');
INSERT INTO country (id, name, code) VALUES (148,'Mozambique','mz');
INSERT INTO country (id, name, code) VALUES (149,'Myanmar','mm');
INSERT INTO country (id, name, code) VALUES (150,'Namibia','na');
INSERT INTO country (id, name, code) VALUES (151,'Nauru','nr');
INSERT INTO country (id, name, code) VALUES (152,'Nepal','np');
INSERT INTO country (id, name, code) VALUES (153,'Netherlands Antilles','an');
INSERT INTO country (id, name, code) VALUES (154,'Netherlands','nl');
INSERT INTO country (id, name, code) VALUES (155,'Neutral Zone (no longer exists)','nt');
INSERT INTO country (id, name, code) VALUES (156,'New Caledonia','nc');
INSERT INTO country (id, name, code) VALUES (157,'New Zealand','nz');
INSERT INTO country (id, name, code) VALUES (158,'Nicaragua','ni');
INSERT INTO country (id, name, code) VALUES (159,'Niger','ne');
INSERT INTO country (id, name, code) VALUES (160,'Nigeria','ng');
INSERT INTO country (id, name, code) VALUES (161,'Niue','nu');
INSERT INTO country (id, name, code) VALUES (162,'Norfolk Island','nf');
INSERT INTO country (id, name, code) VALUES (163,'Northern Mariana Islands','mp');
INSERT INTO country (id, name, code) VALUES (164,'Norway','no');
INSERT INTO country (id, name, code) VALUES (165,'Oman','om');
INSERT INTO country (id, name, code) VALUES (166,'Pakistan','pk');
INSERT INTO country (id, name, code) VALUES (167,'Palau','pw');
INSERT INTO country (id, name, code) VALUES (168,'Panama','pa');
INSERT INTO country (id, name, code) VALUES (169,'Papua New Guinea','pg');
INSERT INTO country (id, name, code) VALUES (170,'Paraguay','py');
INSERT INTO country (id, name, code) VALUES (171,'Peru','pe');
INSERT INTO country (id, name, code) VALUES (172,'Philippines','ph');
INSERT INTO country (id, name, code) VALUES (173,'Pitcairn','pn');
INSERT INTO country (id, name, code) VALUES (174,'Poland','pl');
INSERT INTO country (id, name, code) VALUES (175,'Portugal','pt');
INSERT INTO country (id, name, code) VALUES (176,'Puerto Rico','pr');
INSERT INTO country (id, name, code) VALUES (177,'Qatar','qa');
INSERT INTO country (id, name, code) VALUES (178,'Romania','ro');
INSERT INTO country (id, name, code) VALUES (179,'Russian Federation','ru');
INSERT INTO country (id, name, code) VALUES (180,'Rwanda','rw');
INSERT INTO country (id, name, code) VALUES (181,'Réunion','re');
INSERT INTO country (id, name, code) VALUES (182,'Saint Lucia','lc');
INSERT INTO country (id, name, code) VALUES (183,'Samoa','ws');
INSERT INTO country (id, name, code) VALUES (184,'San Marino','sm');
INSERT INTO country (id, name, code) VALUES (185,'Sao Tome & Principe','st');
INSERT INTO country (id, name, code) VALUES (186,'Saudi Arabia','sa');
INSERT INTO country (id, name, code) VALUES (187,'Senegal','sn');
INSERT INTO country (id, name, code) VALUES (188,'Seychelles','sc');
INSERT INTO country (id, name, code) VALUES (189,'Sierra Leone','sl');
INSERT INTO country (id, name, code) VALUES (190,'Singapore','sg');
INSERT INTO country (id, name, code) VALUES (191,'Slovakia','sk');
INSERT INTO country (id, name, code) VALUES (192,'Slovenia','si');
INSERT INTO country (id, name, code) VALUES (193,'Solomon Islands','sb');
INSERT INTO country (id, name, code) VALUES (194,'Somalia','so');
INSERT INTO country (id, name, code) VALUES (195,'South Africa','za');
INSERT INTO country (id, name, code) VALUES (196,'South Georgia and the South Sandwich Islands','gs');
INSERT INTO country (id, name, code) VALUES (197,'Spain','es');
INSERT INTO country (id, name, code) VALUES (198,'Sri Lanka','lk');
INSERT INTO country (id, name, code) VALUES (199,'St. Helena','sh');
INSERT INTO country (id, name, code) VALUES (200,'St. Kitts and Nevis','kn');
INSERT INTO country (id, name, code) VALUES (201,'St. Pierre & Miquelon','pm');
INSERT INTO country (id, name, code) VALUES (202,'St. Vincent & the Grenadines','vc');
INSERT INTO country (id, name, code) VALUES (203,'Sudan','sd');
INSERT INTO country (id, name, code) VALUES (204,'Suriname','sr');
INSERT INTO country (id, name, code) VALUES (205,'Svalbard & Jan Mayen Islands','sj');
INSERT INTO country (id, name, code) VALUES (206,'Swaziland','sz');
INSERT INTO country (id, name, code) VALUES (207,'Sweden','se');
INSERT INTO country (id, name, code) VALUES (208,'Switzerland','ch');
INSERT INTO country (id, name, code) VALUES (209,'Syrian Arab Republic','sy');
INSERT INTO country (id, name, code) VALUES (210,'Taiwan, Province of China','tw');
INSERT INTO country (id, name, code) VALUES (211,'Tajikistan','tj');
INSERT INTO country (id, name, code) VALUES (212,'Tanzania, United Republic of','tz');
INSERT INTO country (id, name, code) VALUES (213,'Thailand','th');
INSERT INTO country (id, name, code) VALUES (214,'Togo','tg');
INSERT INTO country (id, name, code) VALUES (215,'Tokelau','tk');
INSERT INTO country (id, name, code) VALUES (216,'Tonga','to');
INSERT INTO country (id, name, code) VALUES (217,'Trinidad & Tobago','tt');
INSERT INTO country (id, name, code) VALUES (218,'Tunisia','tn');
INSERT INTO country (id, name, code) VALUES (219,'Turkey','tr');
INSERT INTO country (id, name, code) VALUES (220,'Turkmenistan','tm');
INSERT INTO country (id, name, code) VALUES (221,'Turks & Caicos Islands','tc');
INSERT INTO country (id, name, code) VALUES (222,'Tuvalu','tv');
INSERT INTO country (id, name, code) VALUES (223,'Uganda','ug');
INSERT INTO country (id, name, code) VALUES (224,'Ukraine','ua');
INSERT INTO country (id, name, code) VALUES (225,'Union of Soviet Socialist Republics (no longer exists)','su');
INSERT INTO country (id, name, code) VALUES (226,'United Arab Emirates','ae');
INSERT INTO country (id, name, code) VALUES (227,'United Kingdom (Great Britain)','gb');
INSERT INTO country (id, name, code) VALUES (228,'United States Minor Outlying Islands','um');
INSERT INTO country (id, name, code) VALUES (229,'United States Virgin Islands','vi');
INSERT INTO country (id, name, code) VALUES (230,'United States','us');
INSERT INTO country (id, name, code) VALUES (231,'Uruguay','uy');
INSERT INTO country (id, name, code) VALUES (232,'Uzbekistan','uz');
INSERT INTO country (id, name, code) VALUES (233,'Vanuatu','vu');
INSERT INTO country (id, name, code) VALUES (234,'Vatican City State (Holy See)','va');
INSERT INTO country (id, name, code) VALUES (235,'Venezuela','ve');
INSERT INTO country (id, name, code) VALUES (236,'Viet Nam','vn');
INSERT INTO country (id, name, code) VALUES (237,'Wallis & Futuna Islands','wf');
INSERT INTO country (id, name, code) VALUES (238,'Western Sahara','eh');
INSERT INTO country (id, name, code) VALUES (239,'Yemen','ye');
INSERT INTO country (id, name, code) VALUES (240,'Yugoslavia','yu');
INSERT INTO country (id, name, code) VALUES (241,'Zaire','zr');
INSERT INTO country (id, name, code) VALUES (242,'Zambia','zm');
INSERT INTO country (id, name, code) VALUES (243,'Zimbabwe','zw');
